### ISSUE TITLE
Comments disappearing when moving Cards

### ISSUE THREAD

**Issue by Erik-eMP** [RestyaPlatform/board#1371]
## Expected Behavior
1. Add a comment on a Card 'There is a bug in xxxxx, this should be checked by QA'
2. Move the Card to another Board like 'QA Board'
3. The Card is moved including the comments

## Current Behavior
1. Add a comment on a Card
2. Move the Card
3. The Card is moved, but the comments are discarded
## Possible Solution
Let the comments stay on the Cards. A lot of communication is lost and you need an admin to copy-paste the comments into the description.

## Steps to Reproduce (for bugs)
1. Add a comment on a Card
2. Move the Card
3. The Card is moved, but the comments are discarded

## Context
When working with several teams with several members, a task/card can have a work-flow across boards. Communication such as comments should never be lost in a task and communication platform that is optimising the internal tasks and communication process.

## Your Environment
MacOS, Chrome
* Link to your project: project.emailplatform.com

**Comment by rrjanbiah** [comment]
@lmarikannan Another user Krill also has mentioned same issue. Have to give high priority.

In my workflow I'm constantly moving cards from board to board and from list to list so that the card is a ticket. And I need their hash-numbers in my off-Internet activity for example I put hash-numbers on clients devices during repair (or just storage) process and so on. So (in Trello I'm using now) problem is it drops all the cards history during moving cards between boards, and two days ago I discovered it even changes hash-numbers related to cards. So that workflow I designed seems to be broken :) So my question is: does restyaboard using the same concept (in my scenario) or not.

**Comment by Yasharah** [comment]
the same thing happens if some user is writing a comment and some other user moves a card on the bord at the same time...then the typed comment just disappears and you can start from scratch. that is a critical bug...

**Comment by lmarikannan** [comment]
@Yasharah @Erik-eMP Yes. We are working on this issue and will update on this shortly.

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/0858f5e98d2a4c6533662c8dacd4554150acdd6a

**Comment by Yasharah** [comment]
i also have the problem with cards that have many checklists/checklistoptions that comments just disappear. the are there after your wrote them, but they are not there anymore after you clos the card and open it again. you still see the speech bubble on the card but there are no comments...i hope this fixes that too
