### ISSUE TITLE
Gant chart view squashed

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#433]
A picture tells more tha words:
http://imgur.com/bbHGsqa

No errors in the nginx log on this one. Issue reprodusable with Firefox 45.0 and MS Edge and different users.

**Comment by rrjanbiah** [comment]
@Zimeon- Sorry for the trouble. Will fix it soon.

**Comment by ssivachidambaram** [comment]
We have noted and fixed in v0.2. Please refer #389. Can you please check after clear cache and let us know if this issue still reproduced?

**Comment by Zimeon-** [comment]
We didn't have the issue with 0.1.6 and noticed it after upgrading to 0.2.0. Cleared browser cache and server php-fpm cache. Anyhting else we should try?

**Comment by ssivachidambaram** [comment]
![gantt-chart](https://cloud.githubusercontent.com/assets/91407/13746595/1fcd7e4e-ea1a-11e5-83ae-2048159ffafa.png)

We have checked in Firefox version 45.0, its working fine for us in Restyboard version 2.0. Can you please check this URL http://board.demo.restya.com/#/board/7/gantt and let us know?

**Comment by Zimeon-** [comment]
That one seems to work. Is there some other cache I should try to empty? Tried to clear all stored browser data on MS Edge. Clearing Edge browser  cache had no impact. Same issue with a another PC and browser.

**Comment by ssivachidambaram** [comment]
Can you please check in private window in Edge browser?

**Comment by Zimeon-** [comment]
Same thing.

http://imgur.com/wDh7qWQ (MS Edge private mode)
http://imgur.com/rOuPlDg (Firefox private mode)

**Comment by rrjanbiah** [comment]
@ssivachidambaram There is undefined error in the screenshot. Probably due to wrong JSON serialization (hand coded or so)?

**Comment by ssivachidambaram** [comment]
It was created problem while due date set as from date in Gantt. Now we have fixed this in v0.2.1.

**Comment by edouard-lopez** [comment]
Still got a buggy rendering .

### Env

* Restya `v0.2.1` (2016-03-16)
  * via [Docker-restya](https://github.com/namikingsoft/docker-restyaboard)
* Firefox `45.0`

### Tried 

1. clearing cache ;
2. private mode.

Here is [my _board.json_ file](https://gist.github.com/edouard-lopez/d0c9ebd6f287b907f79c) if that might help

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. We will check and update you shortly.

**Comment by Zimeon-** [comment]
Same here, still the same issue. See these messages in the browser:
NaN
undefined

**Comment by rrjanbiah** [comment]
Update: Further to my discussion with @ssivachidambaram it seems to arise due to different date format coming from different machines (`2016-03-15T22:34:48.100683` Vs. `2016-03-15 22:34:48.100683`).

As per PostgreSQL documentation, it has to be without `T`  http://www.postgresql.org/docs/current/static/datatype-datetime.html

> Note: ISO 8601 specifies the use of uppercase letter T to separate the date and time. PostgreSQL accepts that format on input, but on output it uses a space rather than T, as shown above. This is for readability and for consistency with RFC 3339 as well as some other database systems.

**Comment by rrjanbiah** [comment]
@Zimeon- @edouard-lopez 

As per our understanding PostgreSQL is returning date with `T` in it and in our systems, it is returning without such `T` which is expected PostgreSQL behavior.

Even by googling, we couldn't figure out why it happens so. We're also unsure if it is a bug in PostgreSQL. 

Do you guys have any suggestion here? Could it be due to any environment settings?

**Comment by edouard-lopez** [comment]
@rrjanbiah I'm using the [Docker-restya](https://github.com/namikingsoft/docker-restyaboard) to set up my instance, you can easily try it and reproduce my env.

From what I see in its [docker-entrypoint.sh](https://github.com/namikingsoft/docker-restyaboard/blob/6f63d86241cf0162b317692915c1d274c2921f00/docker-entrypoint.sh#L46), the **database is created with `UTF8 `encoding**: 

    psql -c "CREATE DATABASE restyaboard ENCODING 'UTF8'"

Might be good to **check your db is the encoding**/locale/collation.

**Comment by rrjanbiah** [comment]
@edouard-lopez Thanks a lot for your suggestion. Will definitely try that.

**Comment by Zimeon-** [comment]
My database is en_US.UTF-8 as well. As @edouard-lopez mentioned it's most likely an issue with how you handle the different encodings. 

As a side note, pgadmin shows the due dates consistently but in our case we have one card which due date is set to 2017. Could this cause issues? Mayby limit due date time to +-30 days and give an option to show more?

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your note. We'll try to fix it as soon as possible.

**Comment by ssivachidambaram** [comment]
Fixed.

**Comment by rrjanbiah** [comment]
For the sake of record: We couldn't reproduce the environment of @Zimeon- and @edouard-lopez even using docker version. And so, we updated with common workaround for all machines. CC @ssivachidambaram
